### PR TITLE
Debian netboot

### PR DESCRIPTION
**Pull request by pietrushnic**

### CODE REVIEW

**Comment by pietrushnic** [comment]
@konopskyyy please take a look at this test

**Comment by pietrushnic** [comment]
@konopskyyy `reboot_to_uefi_shell.robot` is WIP, but rest should be reviewed. There are probably some best known methods I'm not following.

**Comment by konopskyyyy** [comment]
@pietrushnic my account is @konopskyyyy, not @konopskyyy :)
about test:
looks ok but tests should be independent. In the future, we need to separate them using our keywords

**Comment by pietrushnic** [comment]
@konopskyyyy ok I will use other account. Can I assume you are ok with merging ? You will have to deal with redesign, so you have last word.

**Comment by konopskyyyy** [comment]
@pietrushnic I think you can merge it.

**Pull request merged**
